### ISSUE TITLE
error parsing xmlstatus: cannot find running info in: RUNNING (13) (TLS)

### ISSUE THREAD

**Issue by idanielblake** [rif/telegraf-freeswitch#2]
Hi, I enabled tls in internal profile. after that plugin does not work anymore with this error:
error parsing xmlstatus: cannot find running info in: RUNNING (13) (TLS)
Thanks

**Comment by rif** [comment]
Hi @idanielblake , please share here the minimum configuration changes from a vanilla FreeSWITCH that reproduce your issue.

**Comment by rif** [comment]
please run the following command in the terminal on the freeswitch box:
```shell
fs_cli -x "sofia xmlstatus"
```

**Comment by idanielblake** [comment]
I replaced server ip address with ip.address. also removed my gateways.

<?xml version="1.0" encoding="ISO-8859-1"?>
<profiles>
<profile>
<name>external</name>
<type>profile</type>
<data>sip:mod_sofia@ip.address:5080</data>
<state>RUNNING (0)</state>
</profile>

<profile>
<name>internal</name>
<type>profile</type>
<data>sip:mod_sofia@ip.address:5060</data>
<state>RUNNING (0)</state>
</profile>
<profile>
<name>internal</name>
<type>profile</type>
<data>sip:mod_sofia@ip.address:5061</data>
<state>RUNNING (0) (TLS)</state>
</profile>
</profiles>

**Comment by idanielblake** [comment]
sorry. github removed xml tags.

**Comment by rif** [comment]
I think I understand the problem, will make a new release soon

**Comment by idanielblake** [comment]
Thank you so much

**Comment by rif** [comment]
please check the latest release

**Comment by idanielblake** [comment]
it's working now :)
