### ISSUE TITLE
Could not find address info

### ISSUE THREAD

**Issue by 00Asgaroth00** [rif/telegraf-freeswitch#4]
Hi,

When attempting to run a one-shot cli of telegraf-freeswitch v2.0.1 I am presenten with the following error:

```
# ./telegraf-freeswitch -host 1.1.1.1 -port 8021 
error parsing xmlstatus: could not find address info in: sip:profile_name@1.1.1.1:10112
```
When parsing the profiles address details are you also accomadating for the listen port as well?
We have multiple profiles on the same address but listening on different ports.

Please let me know if you need any additional info to help debug this issue.

INFO: ip details masked

**Comment by rif** [comment]
I was expecting the data field from xmslstatus to be of form:

```
^sip:mod_sofia@(.+):\d+
```

Relaxed the regular expression to accept your output and also include the port in the output.
Made a new minor relase,  please test and report any issues.

**Comment by 00Asgaroth00** [comment]
I can confirm that version 2.0.2 works as advertised.
Thanks for the quick fix!

I've encountered a different error on older freeswitch systems, but I'l open a separate issue for that.
