### ISSUE TITLE
json command not found

### ISSUE THREAD

**Issue by 00Asgaroth00** [rif/telegraf-freeswitch#5]
When running a one-shot execution of telegraf-freeswitch v2.0.2 against older freeswitch versions (specifically, freeswitch versions 1.2), I am presented with the following error:

```
# ./telegraf-freeswitch -host 1.1.1.1 -pass 'my_password'
error sending status command: json Command not found!
```
I'm guessing newer versions added the json api call, whereas v1.2 did not have it (unless I'm mistaken)

Any chance of having a workaround in these cases?

**Comment by rif** [comment]
Please paste a status command output as appears in that version, will fallback to plain regex parsing of the output if json fails. 

e.g.

```
UP 0 years, 5 days, 22 hours, 57 minutes, 29 seconds, 479 milliseconds, 830 microseconds
FreeSWITCH (Version 1.8.5 -6-31281a0bf1 64bit) is ready
0 session(s) since startup
0 session(s) - peak 0, last 5min 0 
0 session(s) per Sec out of max 300, peak 0, last 5min 0 
10000 session(s) max
min idle cpu 0.00/99.00
Current Stack Size/Max 240K/8192K
```

**Comment by 00Asgaroth00** [comment]
Hi,

Here;s a sample from an affected host:
```
> status
UP 0 years, 207 days, 9 hours, 5 minutes, 40 seconds, 521 milliseconds, 268 microseconds
FreeSWITCH (Version 1.2.23  64bit) is ready
18169728 session(s) since startup
140 session(s) - peak 342, last 5min 142 
11 session(s) per Sec out of max 80, peak 42, last 5min 14 
1000 session(s) max
min idle cpu 0.00/62.00
Current Stack Size/Max 240K/8192K
```

**Comment by rif** [comment]
Made another version with text parsing fallback.

Please test

**Comment by 00Asgaroth00** [comment]
Just gave it a test and am now getting the following error messages:

```
error parsing status command: invalid character 'U' looking for beginning of value &{Status: Response:{Sessions:{Count:{Total:0 Active:0 Peak:0 Peak5min:0 Limit:0} Rate:{Current:0 Max:0 Peak:0 Peak5min:0}} StackSize:{Current:0 Max:0}}}
```

**Comment by rif** [comment]
my bad, please try again

**Comment by 00Asgaroth00** [comment]
no problemo :)

I now get this error with v2.2.1

```
error sending status command: <nil>
```

**Comment by rif** [comment]
we are making progress :)

I guess it wanted to have v2.2.2 as it looks better... Please try again!

**Comment by 00Asgaroth00** [comment]
excellent, v2.2.2 seems to do what it says on the tin.

thanks for the speedy fixes!
