### ISSUE TITLE
typo in cli parameter for server mode

### ISSUE THREAD

**Issue by 00Asgaroth00** [rif/telegraf-freeswitch#6]
Looking at the help output for telegraf-freeswitch it appears there may be a typo for server mode:

```
  -serve
        run as a server
```
Should the parameter not be "-server" instead of "-serve"

**Comment by rif** [comment]
I meant it as a verb and anyhow I guess we should not change it now to maintain backward compatibility in case someone is using it.

**Comment by 00Asgaroth00** [comment]
Ah-ha, I see now what you meant. Soyry for the noise :)
